version: 2
jobs:
  build:
    working_directory: '~/pnut'
    docker:
      - image: 'blueflag/client-build:0.0.7'

    steps:
      - 'checkout'
      - restore_cache: {keys: ['v1-root-{{ checksum "yarn.lock" }}']}
      - run: 'yarn install'
      - run: 'yarn build'
      - save_cache: {paths: ['node_modules'], key: 'v1-root-{{ checksum "yarn.lock" }}'}

      - run: 'git diff | cat'
      - run: 'test -z "$(git status --porcelain)"'
      - run: 'yarn test-all'

